config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"



resources :carts
resources :products  
resources :orders
resources :order_items

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  before_save :update_subtotal
  
  def add_order_items_from_cart(cart)
    cart.order_items.each do |item|
      item.cart_id = nil
      order_items << item
    end
  end
  

 private
 def update_subtotal
    self[:subtotal] = subtotal
  end

 end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.paginate :page=>params[:page], :order=>'created_at desc',
    :per_page => 10
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @orders }
    end
  end
  def create
      @order = Order.new(params[:order])
      @order.add_order_items_from_cart(current_cart)
      respond_to do |format|
        if @order.save
          Cart.destroy(session[:cart_id])
          session[:cart_id] = nil
          format.html { redirect_to(root_url, :notice =>
          'Thank you for your order.') }
          format.xml { render :xml => @order, :status => :created,
          :location => @order }
        else
          format.html { render :action => "new" }
          format.xml { render :xml => @order.errors,
          :status => :unprocessable_entity }
        end
      end
    end


  def new
    @cart = current_cart
    if @cart.order_items.empty?
      redirect_to root_url, :notice => "Your cart is empty"
      return
    end

    @order = Order.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @order }
    end
  end 
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
<tr>
<th>Name</th>
<th>Address</th>
<th>Email</th>
<th>Pay type</th>
<th></th>
<th></th>
<th></th>
</tr>
<% @orders.each do |order| %>
<tr>
<td><%= order.name %></td>
<td><%= order.address %></td>
<td><%= order.email %></td>
<td><%= order.pay_type %></td>
<td><%= link_to 'Show', order %></td>
<td><%= link_to 'Edit', edit_order_path(order) %></td>
<td><%= link_to 'Destroy', order, :confirm => 'Are you sure?',
:method => :delete %></td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New Order', new_order_path %>
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :total_price %><br>
    <%= f.number_field :total_price %>
  </p>
  <p>
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </p>
  
  <p>
    <%= link_to 'Pay', cart_path(@cart), class: 'btn btn-primary', method: :post %>
        <%= form_tag orders_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            
          </article>

         <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-email="<%= current_user.email %>"
                  data-description="<%= @order %> (<%= number_to_currency @order.total_price %>)"
                  data-amount="<%= (@order.total_price.to_i * 100) %>"
                  data-locale="auto"></script>
  <% end %>   
    
  </p>
<% end %>

app/views/orders/show.html.erb
<h1>Show order</h1>