config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"



resources :carts
resources :products  
resources :orders
resources :order_items

end

app/models/product.rb
class Product < ApplicationRecord
  
  validates :name, presence: true
  validates :picture, presence: true
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :order_items
  has_many :carts, through: :order_items

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def index
    @products = Product.paginate(page: params[:page], per_page:6)
    @cart = current_cart
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    return render_not_found if @product.blank?
    return render_not_found(:forbidden) if @product.user != current_user
    @product.destroy
    redirect_to root_path
  end


  def update
    @product = Product.find_by_id(params[:id])
    return render_not_found if @product.blank?
    return render_not_found(:forbidden) if @product.user != current_user
    
    @product.update_attributes(product_params)
    
    if @product.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find_by_id(params[:id])
    return render_not_found if @product.blank?
    return render_not_found(:forbidden) if @product.user != current_user
  end

  def show
    @product = Product.find_by_id(params[:id])
    return render_not_found if @product.blank?
    
  end

  def create
    @product = current_user.products.create(product_params)
    if @product.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def display_cart
    @cart = find_cart
    @items = @cart.items
  end

  def add_to_cart
    product = Product.find(params[:id])
    @cart = find_cart
    @cart.add_product(product)
    redirect_to(:action => 'display_cart')
  end


private

  def product_params
    params.require(:product).permit(:name, :price, :description, :picture)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/display_cart.html.erb
<h1>Display Cart</h1>
<table>
<%
for item in @items
product = item.product
-%>
<tr>
<td><%= item.quantity %></td>
<td><%= h(product.title) %></td>
<td align="right"><%= item.unit_price %></td>
<td align="right"><%= item.unit_price * item.quantity %></td>
</tr>
<% end -%>
</table>

app/views/products/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Product</h2>
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
  <%= f.submit %>
<% end %>
</div>

app/views/products/index.html.erb
<%= will_paginate @products %>
    
  
      <% @products.each do |product| %>
      <div class="container-fluid">
        <div class="row">
          <div class="col-3">
            <div class="booyah-box col-10 offset-1">
              <div class="card" style="width: 18rem">
                <%= link_to product_path(product) do %>
                  <%= image_tag product.picture.to_s, class: 'img-fluid' %>
                <% end %>
                <div class="handle"><%= product.user.email %></div>
                <div class="row">
                <div class="col-sm-8 col-12">
                <p><%= link_to product.name, product_path(product) %>
                <br/>
                <%= number_to_currency(product.price) %></p>
                <p><%= product.description %></p>
                <div class="product-actions float-right">
                <% if current_user && current_user == product.user %>
                <%= link_to "Edit", edit_product_path(product) %> |
                <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
                <% end %>
                </div>
              <div class="handle">
              <%= button_to "Add to Cart", order_items_path(product_id: product), class: 'btn btn-primary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div>
<% end %>




</div>


<p><%= link_to "New product", new_product_path %></p>






app/views/products/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
<h1>New Product</h1>
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.file_field :picture %>
  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/products/show.html.erb
<%= @product.inspect %>


<div class="booyah-box col-10 offset-1">
  
    <h1><%= @product.name %></h1>
    <%= image_tag @product.picture.to_s, class: 'img-fluid' %>
    <br />
    <div class="row">
    <div class="col-sm-4 col-12 text-center">
    <span class="badge badge-default">
      <%= number_to_currency @product.price %>
    </span>
    <br/>
    <p>
      <%= @product.description %>
    </p>
    
    <%= link_to 'Back', products_path %>
      
    </div>
   
   

</div>
</div>
</div>